package com.paulsoja.githubissues.domain.model.user

data class User(
    val id: Int,
    val name: String,
    val username: String,
    val state: String,
    val avatarUrl: String,
    val webUrl: String,
    val createdAt: String,
    val bio: String,
    val location: String,
    val publicEmail: String,
    val skype: String,
    val linkedin: String,
    val twitter: String,
    val websiteUrl: String,
    val organization: String,
    val lastSignInAt: String,
    val confirmedAt: String,
    val lastActivityOn: String,
    val email: String,
    val themeId: String,
    val colorSchemeId: Int,
    val projectsLimit: Int,
    val currentSignInAt: String,
    val identities: List<Identities> = listOf(),
    val canCreateGroup: Boolean,
    val canCreateProject: Boolean,
    val twoFactorEnabled: Boolean,
    val external: Boolean,
    val privateProfile: Boolean,
    val sharedRunnersMinutesLimit: Int,
    val extraSharedRunnersMinutesLimit: Int
)